py_library(
    name = "nuscenes",
    srcs = [
        "__init__.py",
        "nuscenes.py",
        "lidarseg/lidarseg_utils.py",
        "panoptic/panoptic_utils.py",
    ] + glob(["utils/*.py"]),
    deps = [],
    visibility = ["//visibility:public"],
)
