FROM continuumio/miniconda3:4.6.14
ENV PATH /opt/conda/bin:$PATH
ENV PYTHONPATH=/nuscenes-dev/python-sdk

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libgl1-mesa-glx \
        libglib2.0-0 \
        xvfb && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /nuscenes-dev
COPY setup/requirements.txt /nuscenes-dev
# Install Python dependencies inside of the Docker image via Conda.
RUN bash -c "conda create -y -n nuscenes python=3.6; source activate nuscenes && \
    pip install -r /nuscenes-dev/requirements.txt \
    && conda clean --yes --all"

COPY . /nuscenes-dev
