apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nuscenes-docker
spec:
  containers:
  - name: jnlp
    image: registry.nutonomy.com:5000/nu/jnlp-slave:3.19-1-lfs
    imagePullPolicy: Always
  - name: docker
    image: registry.nutonomy.com:5000/nu/docker-bash:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker
  imagePullSecrets:
  - name: regcredjenkins
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
