name: nuscenes-devkit CI pipeline
on: [pull_request]
env:
  NUSCENES: data/sets/nuscenes
  NUIMAGES: data/sets/nuimages
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install datasets
        run: |
          mkdir -p ${NUSCENES} && mkdir -p ${NUIMAGES}
          curl -fsSL https://motional-nuscenes.s3-ap-northeast-1.amazonaws.com/public/v1.0/v1.0-mini.tgz | tar -xzvf - -C ${NUSCENES} --exclude sweeps
          curl -fsSL https://motional-nuscenes.s3-ap-northeast-1.amazonaws.com/public/nuimages-v1.0/nuimages-v1.0-mini.tgz | tar -xzvf - -C ${NUIMAGES}
          curl -fsSL https://motional-nuscenes.s3-ap-northeast-1.amazonaws.com/public/nuscenes-lidarseg-v1.0/nuScenes-lidarseg-mini-v1.0.tar.bz2 | tar -xzvf - -C ${NUSCENES}
          curl -fsSL https://motional-nuscenes.s3-ap-northeast-1.amazonaws.com/public/nuscenes-panoptic-v1.0/nuScenes-panoptic-v1.0-mini.tar.gz | tar -xzvf - --strip-components=1 -C ${NUSCENES}

          curl -fsSL https://motional-nuscenes.s3-ap-northeast-1.amazonaws.com/public/v1.0/nuScenes-map-expansion-v1.3.zip
          unzip nuScenes-map-expansion-v1.3.zip -d ${NUSCENES}/maps/
          curl https://motional-nuscenes.s3-ap-northeast-1.amazonaws.com/public/v1.0/can_bus.zip
          unzip can_bus.zip -d ${NUSCENES} can_bus/scene-0001_*
          rm nuScenes-map-expansion-v1.3.zip can_bus.zip

          du -hs ${NUSCENES}
          du -hs ${NUIMAGES}